services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-flash}
      - MAX_CONVERSATION_HISTORY=${MAX_CONVERSATION_HISTORY:-50}
      - ESCALATION_KEYWORDS=${ESCALATION_KEYWORDS:-refund,cancel,complaint,manager,human,representative}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:
    driver: local
