plugins:
  - id: express
    type: "@godspeedsystems/plugins-express-as-http"
    port: 3000
    base_url: /api/v1
    
  - id: redis
    type: "@godspeedsystems/plugins-redis-as-datasource"
    host: localhost
    port: 6379
    
log:
  level: info
  
ai:
  provider: openai
  model: gpt-3.5-turbo
  max_tokens: 500
  temperature: 0.7
  
chat:
  max_history: 10
  session_timeout: 1800000
  escalation_keywords:
    - urgent
    - emergency
    - complaint
    - supervisor
    - manager
    - cancel
    - refund
